services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # Do not change

    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # Do not change
      - /var/run/docker.sock:/var/run/docker.sock:ro # If changed, set 'WATCHTOWER_DOCKER_SOCKET_PATH'!

    # See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    ports:
      - 8080:8080
      # - 80:80 # Keep commented if running behind Caddy
      # - 8443:8443 # AIO UI - Keep commented if behind Caddy

    environment:
      - APACHE_PORT=11000 # Needed when behind Caddy
      - APACHE_IP_BINDING=127.0.0.1 # Run server on localhost and proxy via Caddy 
      - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=2 --keep-monthly=2 # See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      - NEXTCLOUD_DATADIR=/data/nextcloud/ncdata # Set the host directory for Nextcloud's datadir. DO NOT CHANGE AFTER FIRST SETUP. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_UPLOAD_LIMIT=20G # See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      - NEXTCLOUD_MEMORY_LIMIT=8192M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick smbclient # See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true # See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud  

      # - NEXTCLOUD_MOUNT=/data/ # Gives nextcloud access to the whole data partition. Probably insecure. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - AIO_DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature 
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # - NEXTCLOUD_ADDITIONAL_APKS=imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_KEEP_DISABLED_APPS=false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
    # networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      # - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # Do not change
