---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1009
      - PGID=1003
      - TZ=Etc/UTC
    volumes:
      - /data/config/sonarr:/config
      - /data/media:/data/media
    ports:
      - 8989:8989
    restart: unless-stopped

